export default {
  generateMarkdown (data) {
    if (data.type === 'bug') {
      return this.generateBugMarkdown(data)
    } else if (data.type === 'feature') {
      return this.generateFeatureMarkdown(data)
    }
  },
  generateBugMarkdown (data) {
    let md = `
### Versions and Environment
Vuetify: ${data.vuetifyVersion}
Vue: ${data.vueVersion}
Browsers: ${data.browsers}
OS: ${data.os}

### Expected Behavior
${data.expected}

### Actual Behavior
${data.actual}

### Reproduction Link
[${data.link}](${data.link})

### Other comments
${data.other}

<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->
    `
    return md
  },
  generateFeatureMarkdown (data) {
    let md = `
### New Functionality
${data.whatsNew}

### Improvements
${data.whatsImproved}

### Bugs or Edge Cases it Helps Avoid
${data.whatsAvoided}

<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->
    `
    return md
  }
}
